sudo: required

services:
  - docker

before_install: 
  - docker build -t nickskiejoi/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true nickskiejoi/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: Docker-react-app-1
  env: Docker-react-app-1-env
  bucket_name: elasticbeanstalk-ap-southeast-1-527683503049
  bucket_path: Docker-react
  on:
    branch: master

  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"

